Restopos.Yoklama.Web/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Restopos.Yoklama.Business.Interfaces;
using Restopos.Yoklama.Entities.Concrete;
using Restopos.Yoklama.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restopos.Yoklama.Web.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        private readonly IUserService userService;
        public PanelController(IUserService userService)
        {
            this.userService = userService;
        }
        public IActionResult Index()
        {
            var user = userService.GetByUsername(User.Identity.Name);

            UserSummaryViewModel model = new UserSummaryViewModel
            {
                Id = user.Id,
                Name = user?.Name,
                Surname = user?.Surname,
                Username = user?.Username,
                DepartmentName = user?.Department?.Name
            };

            return View(model);
        }

        public IActionResult ChangePassword(int id)
        {
            ChangePasswordViewModel model = new ChangePasswordViewModel();
            model.UserId = id;

            return View(model);
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = userService.GetById(model.UserId);

                if (model.OldPassword.Equals(model.NewPassword))
                {
                    ModelState.AddModelError("", "Eski şifre ile yeni şifre aynı olamaz.");
                }
                if (!user.Password.Equals(model.OldPassword))
                {
                    ModelState.AddModelError("", "Eski şifrenizi yanlış girdiniz.");
                }

                if (ModelState.ErrorCount > 0)
                {
                    return View(model);
                }

                userService.ChangePassword(new User { Id = model.UserId, Password = model.NewPassword });
                ViewBag.SuccessMessage = "Şifreniz değiştirildi";
                return View();
            }
            return View(model);
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Restopos.Yoklama.Web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Restopos.Yoklama.Business.Interfaces;
using Restopos.Yoklama.Entities.Concrete;
using Restopos.Yoklama.Entities.Concrete.Constants;
using Restopos.Yoklama.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restopos.Yoklama.Web.Controllers
{
    [Authorize(Policy = ConstPrivileges.LIST_ROLES)]
    public class RoleController : Controller
    {
        private readonly IRoleService roleService;
        private readonly IPrivilegeService privilegeService;

        public RoleController(IRoleService roleService, IPrivilegeService privilegeService)
        {
            this.roleService = roleService;
            this.privilegeService = privilegeService;
        }

        public IActionResult Index()
        {
            List<Role> roles = roleService.GetAll();
            List<RoleViewModel> model = new List<RoleViewModel>();

            if (roles?.Count > 0)
            {
                foreach (var item in roles)
                {
                    model.Add(new RoleViewModel
                    {
                        Id = item.Id,
                        Name = item.Name
                    });
                }
            }

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.ADD_ROLE)]
        public IActionResult Add()
        {
            RoleWithPrivilegesViewModel model = new RoleWithPrivilegesViewModel();
            List<Privilege> privileges = privilegeService.GetAll();
            model.PrivilegesWithSelection = new List<PrivilegeSelectionViewModel>();

            if (privileges?.Count > 0)
            {
                foreach (var item in privileges)
                {
                    model.PrivilegesWithSelection.Add(new PrivilegeSelectionViewModel
                    {
                        Description = item.Description,
                        Id = item.Id,
                        Name = item.Name,
                        isSelected = false
                    });
                }
            }

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.ADD_ROLE)]
        [HttpPost]
        public IActionResult Add(RoleWithPrivilegesViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (roleService.GetByName(model.Name) == null)
                {

                    Role role = new Role
                    {
                        Name = model.Name
                    };

                    List<PrivilegeSelectionViewModel> selectedPrivilegeModels =
                        model.PrivilegesWithSelection.FindAll(x => x.isSelected);

                    if (selectedPrivilegeModels?.Count > 0)
                    {
                        List<RolePrivilege> rolePrivileges = new List<RolePrivilege>();

                        foreach (var item in selectedPrivilegeModels)
                        {
                            rolePrivileges.Add(new RolePrivilege { PrivilegeId = item.Id });
                        }

                        role.RolePrivileges = rolePrivileges;
                    }

                    roleService.Add(role);

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Bu isimde bir rol zaten var.");
                }

            }

            return View(model);
        }

        public IActionResult Details(int id)
        {
            Role role = roleService.GetByIdWithDetails(id);
            RoleDetailsViewModel model = new RoleDetailsViewModel();
            model.Id = role.Id;
            model.Name = role.Name;
            model.RolePrivileges = role.RolePrivileges.OrderBy(x=>x.Privilege.Name).ToList();
            model.UserRoles = role.UserRoles;

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.UPDATE_ROLE)]
        public IActionResult Update(int id)
        {
            Role role = roleService.GetByIdWithDetails(id);

            RoleWithPrivilegesViewModel model = new RoleWithPrivilegesViewModel();
            model.Id = role.Id;
            model.Name = role.Name;

            List<Privilege> privileges = privilegeService.GetAll();
            model.PrivilegesWithSelection = new List<PrivilegeSelectionViewModel>();

            if (privileges?.Count > 0)
            {
                foreach (var item in privileges)
                {
                    model.PrivilegesWithSelection.Add(new PrivilegeSelectionViewModel
                    {
                        Description = item.Description,
                        Id = item.Id,
                        Name = item.Name,
                        isSelected = role.RolePrivileges?.FirstOrDefault(x => x.PrivilegeId == item.Id) != null
                    });
                }
            }

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.UPDATE_ROLE)]
        [HttpPost]
        public IActionResult Update(RoleWithPrivilegesViewModel model)
        {
            if (ModelState.IsValid)
            {
                Role searchingRole = roleService.GetByName(model.Name);
                if (model.Name == searchingRole?.Name && model.Id != searchingRole?.Id)
                {
                    ModelState.AddModelError("", "Bu isimde başka bir rol zaten var");
                    return View(model);
                }
                else if (model.Name == ConstRoles.ADMIN)
                {
                    ModelState.AddModelError("", "Admin rolü değiştirelemez");
                    return View(model);
                }

                Role role = new Role
                {
                    Id = model.Id,
                    Name = model.Name
                };

                List<PrivilegeSelectionViewModel> selectedPrivilegeModels =
                    model.PrivilegesWithSelection.FindAll(x => x.isSelected);

                if (selectedPrivilegeModels?.Count > 0)
                {
                    List<RolePrivilege> rolePrivileges = new List<RolePrivilege>();

                    foreach (var item in selectedPrivilegeModels)
                    {
                        rolePrivileges.Add(new RolePrivilege { PrivilegeId = item.Id });
                    }

                    role.RolePrivileges = rolePrivileges;
                }

                roleService.Update(role);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.DELETE_ROLE)]
        public JsonResult Delete(int id)
        {
            try
            {
                if (roleService.GetById(id)?.Name != ConstRoles.ADMIN)
                {
                    roleService.Remove(new Role { Id = id });
                    return Json(null);
                }
                else
                {
                    return Json("Uyarı: Admin rolü silinemez");
                }
            }
            catch (Exception)
            {
                return Json("Hata");
            }

        }
    }
}

Restopos.Yoklama.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Restopos.Yoklama.Business.Interfaces;
using Restopos.Yoklama.Entities.Concrete;
using Restopos.Yoklama.Entities.Concrete.Constants;
using Restopos.Yoklama.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restopos.Yoklama.Web.Controllers
{
    [Authorize(Policy = ConstPrivileges.LIST_USERS)]
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IRoleService roleService;
        private readonly IDepartmentService departmentService;
        public UserController(IUserService userService,
            IRoleService roleService,
            IDepartmentService departmentService)
        {
            this.userService = userService;
            this.roleService = roleService;
            this.departmentService = departmentService;
        }

        public IActionResult Index()
        {
            List<User> users = userService.GetAll();
            List<UserListViewModel> model = new List<UserListViewModel>();
            foreach (var item in users)
            {
                UserListViewModel modelItem = new UserListViewModel
                {
                    Department = item.Department,
                    Id = item.Id,
                    Name = item.Name,
                    Surname = item.Surname,
                    Username = item.Username
                };

                model.Add(modelItem);
            }

            return View(model);
        }

        public ActionResult Details(int id)
        {
            User user = userService.GetByIdWithDetails(id);

            UserDetailsViewModel model = new UserDetailsViewModel();
            model.AbsenceStatuses = user.AbsenceStatuses;
            model.Department = user.Department;
            model.Id = user.Id;
            model.Name = user.Name;
            model.Surname = user.Surname;
            model.Username = user.Username;
            model.Roles = user.UserRoles?.Count > 0 ? SetUserRolestoRoleList(user.UserRoles) : null;

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.UPDATE_USER)]
        public ActionResult Update(int id)
        {
            User user = userService.GetByIdWithDetails(id);
            RoleSelectionViewModel roleModel = new RoleSelectionViewModel();
            List<Role> roles = roleService.GetAll();
            ViewBag.Departments = new SelectList(departmentService.GetAll(), "Id", "Name");

            UserWithRoleSelectViewModel model = new UserWithRoleSelectViewModel
            {
                Department = user.Department,
                Id = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                Username = user.Username
            };

            model.RoleSelections = new List<RoleSelectionViewModel>();
            foreach (var item in roles)
            {
                model.RoleSelections.Add(new RoleSelectionViewModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    isSelected = user.UserRoles?.FirstOrDefault(x => x.RoleId == item.Id) != null
                });
            }

            return View(model);
        }

        [Authorize(Policy = ConstPrivileges.UPDATE_USER)]
        [HttpPost]
        public ActionResult Update(UserWithRoleSelectViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (IsUserNameValid(model.Id,model.Username))
                {
                    User user = new User
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Surname = model.Surname,
                        Username = model.Username,
                        DepartmentId = model.Department?.Id > 0 ? (int?)model.Department.Id : null
                    };

                    model.RoleSelections = model.RoleSelections.FindAll(x => x.isSelected);

                    user.UserRoles = new List<UserRole>();
                    if (model.RoleSelections?.Count > 0)
                    {

                        foreach (var item in model.RoleSelections)
                        {
                            user.UserRoles.Add(new UserRole
                            {
                                RoleId = item.Id
                            });
                        }
                    }

                    userService.Update(user);

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Bu isimde bir kullanıcı adı zaten var.");
                }
               
            }
            ViewBag.Departments = new SelectList(departmentService.GetAll(), "Id", "Name");
            return View(model);
        }


        [Authorize(Policy = ConstPrivileges.DELETE_USER)]
        public JsonResult Delete(int id)
        {
            try
            {
                userService.Remove(new User { Id = id });
                return Json(null);
            }
            catch (Exception ex)
            {
                return Json("Hata");
            }
            
        }


        public JsonResult IsUsernameUnique(int userId, string username)
        {
            return Json(IsUserNameValid(userId, username));
        }

        private bool IsUserNameValid(int userId, string username)
        {
            if (userService.IsUsernameUnique(username))
            {
                return true;
            }
            else if (userService.GetById(userId)?.Username==username)
            {
                return true;
            }
            return false;
        }

        private List<Role> SetUserRolestoRoleList(List<UserRole> userRoles)
        {
            List<Role> roles = new List<Role>();
            foreach (var item in userRoles)
            {
                roles.Add(item.Role);
            }

            return roles;
        }
    }
}

Restopos.Yoklama.Web/Views/Shared/_CustomModal.cshtml
@model (string Header, string Body)

<div class="modal fade" id="customModal" tabindex="-1" aria-labelledby="customModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="customModalLabel">@Model.Header</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @Model.Body
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hayır </button>
                <button type="button" class="btn btn-success" id="btnYes">Evet </button>
            </div>
        </div>
    </div>
</div>

Restopos.Yoklama.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restopos.Yoklama.Web</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Restopos.Yoklama.Web/Views/Shared/_PanelLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/panel.css" rel="stylesheet" />
</head>
<body class="h-100">

    <div class="container-fluid h-100">
        <main role="main" class="h-100">
            <div class="row h-100">
                <div class="col-md-3 @*d-md-inline*@ p-0 bg-info m-0">
                    <div class="sticky-top">
                        <a asp-controller="Panel" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Ana Sayfa</a>
                        <a asp-controller="MyAbsences" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Yoklamam</a>
                        @{
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_USERS))
                            {
                                <a asp-controller="User" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Personel Listesi</a>
                            }
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_USERS_ABSENCES))
                            {
                                <a asp-controller="AbsenceStatus" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Personel Yoklaması</a>
                            }
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_DEPARTMENTS))
                            {
                                <a asp-controller="Department" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Departmanlar</a>
                            }
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_ABSENCETYPES))
                            {
                                <a asp-controller="AbsenceType" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Devamsızlık Türleri</a>
                            }
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_ROLES))
                            {
                                <a asp-controller="Role" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Rol İşlemleri</a>
                            }
                            if (User.HasClaim(x => x.Value == ConstPrivileges.LIST_PRIVILEGES))
                            {
                                <a asp-controller="Privilege" asp-action="Index" class="d-block btn btn-info btn-lg border-bottom rounded-0">Yetki Listesi</a>
                            }
                        }
                        <a asp-controller="Panel" asp-action="LogOut" class="d-block btn btn-info btn-lg border-bottom rounded-0">Çıkış</a>
                    </div>
                </div>
                <div class="col-md-9 pr-md-5 p-3 text-dark">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>